### ISSUE TITLE
Layout issue with large tables

### ISSUE THREAD

**Issue by jeff-matthews** [commerce-docs/devdocs-theme#82]
It only seems to happen at specific screen widths (between 1201 and 1470 pixels). The [System requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) page is a good example.

I'm sure there's a CSS fix for it, but it's a very low priority.

![Screen Shot 2021-08-12 at 12 59 49 PM](https://user-images.githubusercontent.com/13662379/129248022-6ff222ba-e698-4fc2-82fe-1a688501571a.png)

See https://github.com/magento/devdocs/issues/8948.

**Comment by belbiy** [comment]
One solution i might think of is to hide the right side nav on smaller screens.

**Comment by dshevtsov** [comment]
The project is deprecated.
