### ISSUE TITLE
Text under an image doesn't wrap if the browser window is larger than 1546 px.

### ISSUE THREAD

**Issue by dshevtsov** [commerce-docs/devdocs-theme#89]
Text under an image a the end of a section doesn't wrap if the browser window is larger than 1546 px.

_Originally posted by @ccondra in https://github.com/magento-commerce/devdocs/pull/2477#discussion_r694310665_

**Comment by belbiy** [comment]
Should be fixable by adding something like this (but needs further investigation, it's a little bit "dangerous" selector)
```
img + em {
    display: block;
}
```

**Comment by dshevtsov** [comment]
The project is deprecated.
