### ISSUE TITLE
JS bug with the table of contents on scroll

### ISSUE THREAD

**Issue by belbiy** [commerce-docs/devdocs-theme#95]
Something is wrong with TOC on scroll. The plugin supposed to watch the current toc item and scroll the TOC so it always stays in view. Now it's broken.

I suspect it's something to do with changed class names, perhaps script uses old selector that no longer exists.

![Screen Shot 2021-09-22 at 10 05 59 AM](https://user-images.githubusercontent.com/752610/134369954-066f84e3-72bc-4838-a4b9-94c83142493e.png)

**Comment by dshevtsov** [comment]
The project is deprecated.
